spring:
  application:
      name: xmock-satellite
  boot:
    admin:
      client:
        url: http://localhost:9000


server:
   port: 15000


management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'