spring:
  application:
      name: test-service

logging:
  config:
    classpath: logback.xml

server:
   port: 15000


# Display in block info
info:
  environment: dev
  github: https://github.com/snotling/spring-boot-template-client
  documentation: https://github.com/codecentric/spring-boot-admin

management:
  endpoints:
    web:
      exposure:
        include: '*'
# Log file display
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
      external-file: logs/app.log